# -*- restclient -*-
# 
# REST client for Emacs:
# https://github.com/pashky/restclient.el

# Post a blog

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Teach Yourself Programming in Ten Years",
    "author": "Peter Norvig",
    "url": "https://www.norvig.com/21-days.html",
    "likes": 5
}

# Add a user

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "1stein",
    "password": "spacetime",
    "name": "Albert Einstein"
}

# Log in

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "1stein",
    "password": "spacetime"
}